# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - urlnew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6f336295de0e49f8a97191cec4280086 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e6291b45a80341ea868c638a207f1bcd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6f336295de0e49f8a97191cec4280086 }}/girireddychinnu/hello-world-python:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'urlnew'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_84e1796af63a40d299d091080f2ade98 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6f336295de0e49f8a97191cec4280086 }}/girireddychinnu/hello-world-python:${{ github.sha }}'